//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSG.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLog
    {
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public byte IsReturned { get; set; }
        public int ClientId { get; set; }
        public int BookPrintId { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
    
        public virtual BookPrint BookPrint { get; set; }
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
